### ISSUE TITLE
The example script dows not work

### ISSUE THREAD

**Issue by blaisn** [doberkofler/web_plsql#5]
Hi,
After installation , I get an error:
C:\sources\web-plsql>node index
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\sources\web-plsql\index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

The line:
const webplsql = require('../lib');
shouldn't be:
const webplsql = require('web_plsql/lib');
?

Thanks

**Comment by doberkofler** [comment]
Thank you for the information. This dependency problem should now be resolved in 0.2.0.
